# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52a475db35bb139631616f35ee1a96cd6d2004ae86f7f03746cb6da3c7f2bf675ad123734a570722b4bd622739b9bd90f77950fe838d888bd51017d33a6e6884

test:
  secret_key_base: 33b8e5d533ad33ac9c827b9352ca5444b42aea3b74f35eceb7c9afe75dac2ec6fce3d3c8d8b99e547d1017af21676e5b1aa1f7870913579f1daf7e3a3405c442

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
